// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uttdjailbotjmlipaout.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0dGRqYWlsYm90am1saXBhb3V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzODk3MDYsImV4cCI6MjA3Mzk2NTcwNn0.cjOL8CIRgMhyQojBbMF9CCwrBcUDuigsOESMnUa46MY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});